title: "Sebastian Wehrle"
email: "sebastian.wehrle@boku.ac.at"
description: "Economist working on energy and environmental systems."
baseurl: ""
url: "https://sebwehrle.github.io"

markdown: kramdown

theme: minima

include:
  - assets/css/style.css
